require:
  - standard
  - standard-custom
  - standard-performance
  - rubocop-performance
  - rubocop-minitest
  - rubocop-rake

inherit_gem:
  standard: config/base.yml
  standard-custom: config/base.yml
  standard-performance: config/base.yml

AllCops:
  NewCops: enable
  DisplayStyleGuide: true
